#!/bin/bash ####################################################################
#
# Создан:  Ср 14 авг 2013 12:07:22
# Изменён: Пн 13 окт 2014 11:17:37
#
################################################################################
#{{{ \033[00m\n\b------<Cygwin>\n
################################################################################

#- Добавление пути поиска исполнимых файлов Windows
path++ $INIT_PATH          PATH
# path++ /z/bin/win PATH

#- Выполнение команды с помощью cmd.exe
alias winshell="nh cmd.exe /c"

#- Смена логического диска
cd_drive() { #noindex
	# Для пользовательских компьютеров в сети
	if [[ "$(pwd)" == //cb* ]]; then
		cd $(echo `pwd` | sed 's;^//\(.*\)/.*$;//\1;')/${1/:}\$
	else
		cd $1
	fi
}

# Смена логического диска
for drive in $(\df | grep '^[A-Z]:' -o | /usr/bin/sort -u); {
	alias $drive="cd_drive $drive"
	alias $(echo $drive | tr A-Z a-z)="cd_drive $drive"
}

#}}} ###########################################################################
#{{{ \033[00m\n\b------<Windows>\n
################################################################################

#- Подключение к ПК с помощью VNC
vnc() {
	if [[ "$1" == [0-9][0-9].[0-9][0-9] ]]; then
		host="192.168.$1"
	else
		host="$1"
	fi
	winshell 'C:\Program Files\RealVNC\VNC Viewer\vncviewer.exe' $host 2>&1 > /dev/null &
}

#- Подключение по RDP (cb/ts/ms/etc)
rdp() {
	case "$1" in
		cb) host="it-srv-rdp.tkpt.ru";;
		ts) host="srv1.ts.tkpt.ru";;
		ms) host="srv1.ms.tkpt.ru";;
		* ) host="$1";;
	esac
	nh mstsc.exe /v:$host &
}

#- Вызов оснастки Windows
msc() {
	winshell "$1.msc" &
}

#- Вызов компонента Панели управления Windows
cpl() {
	winshell "$1.cpl" &
}

#- Проводник Windows
ex() {
	cygstart -x ${1:-.}
}

#- Вывод net.exe в utf8
net() { #noindex
	$(cygpath "$WINDIR\\system32\\net.exe") $* |& 8U
}

#- ПО
alias iexplore="$(cygpath $SYSTEMDRIVE)/Program\ Files/Internet\ Explorer/iexplore.exe" #noindex
alias firefox="$(cygpath $SYSTEMDRIVE)/Program\ Files/Mozilla\ Firefox/firefox.exe" #noindex
alias 1c8="$(cygpath $SYSTEMDRIVE)/Program\ Files/1cv82/common/1cestart.exe" #noindex
alias far='cmd /c start /max "" "%SYSTEMDRIVE%\Program Files\Far Manager\Far.exe"' #noindex
alias mc="far . ." #noindex

#- Windows: административные утилиты
alias win_all="winshell control admintools &"
#- Windows: просмотр событий
alias win_log="msc eventvwr"
#- Windows: общие ресурсы
alias win_shr="msc fsmgmt"
#- Windows: свойства системы
alias win_sys="cpl sysdm"
#- Windows: установка и удаление программ
alias win_pkg="cpl appwiz"
#- Windows: сетевые подключения
alias win_net="cpl ncpa"
#- Windows: диспетчер устройств
alias win_dev="msc devmgmt"
#- Windows: свойства папки
alias win_dir="control folders"

# Псевдонимы sc_.* нужны для работы дополнения bash

#- Windows: запуск службы
alias sc_start="sc start"
#- Windows: остановка службы
alias sc_stop="sc stop"
#- Windows: приостановление выполнения службы
alias sc_pause="sc pause"
#- Windows: возобновление выполнения службы
alias sc_continue="sc continue"

#- Журнал обновлений Windows
alias wl_update="nl $(cygpath $SYSTEMROOT/WindowsUpdate.log)"

dmesgw() {
	cscript //nologo "$(cygpath -w $SYSTEMROOT/system32/eventquery.vbs)" /FI "type ne INFORMATION" $* | 8U | clr "ошибка"
}

#- Windows: управление принтерами
prn_mngr() { #noindex
	cscript //nologo "$(cygpath -w $SYSTEMROOT/system32/prnmngr.vbs)" $* 2>&1 | 8U
}

prn_drvr() { #noindex
	cscript //nologo "$(cygpath -w $SYSTEMROOT/system32/prndrvr.vbs)" $* 2>&1 | 8U
}

prn_jobs() { #noindex
	cscript //nologo "$(cygpath -w $SYSTEMROOT/system32/prnjobs.vbs)" $* 2>&1 | 8U
}

prn_cnfg() { #noindex
	cscript //nologo "$(cygpath -w $SYSTEMROOT/system32/prncnfg.vbs)" $* 2>&1 | 8U
}

prn_port() { #noindex
	cscript //nologo "$(cygpath -w $SYSTEMROOT/system32/prnport.vbs)" $* 2>&1 | 8U
}

prn_qctl() { #noindex
	cscript //nologo "$(cygpath -w $SYSTEMROOT/system32/prnqctl.vbs)" $* 2>&1 | 8U
}

#- Список выполняемых задач
psw() {
	tasklist.exe $* |& 8U
}

alias ps="\ps au" #noindex

#- Завершение задачи
killw() {
	taskill $* |& 8U
}

#- Установленные пакеты
alias pkgs="cygcheck -c -d | tail -n +3 | nl" #noindex

#- Редактирование псевдонимов
alias ealias="$EDITOR $CYGWIN_ALIASES" #noindex

#}}} ###########################################################################
#{{{ \033[00m\n\b------<TKPT>\n
################################################################################

#- Переход к компьютеру пользователя cb-??-??
cb() {
	cd "//cb-$1/"
}

#- Основные сетевые директории tkpt
alias @install="cd //file-srv/install$/"   #noindex
alias @gpo="cd //file-srv/install$/GPO/"   #noindex
alias @it="cd //file-srv/install$//it/"    #noindex
alias @programs="cd //file-srv/programs$/" #noindex
alias @docs="cd //file-srv/docs$/"         #noindex

#- Список принтеров, опубликованных в AD
alias ad_printers='cscript //nologo $(cygpath -w "`which ldapAllPrinters.vbs`") | 8U'

#- Быстрый доступ к ресурсам
alias beeline="iexplore https://uslugi.beeline.ru &"     #noindex
alias elastix="cygstart -o https://sip.tkpt.ru/index.php &" #noindex

#- Меню на неделю
dinner() {
	cscript //nologo $(cygpath -w "`which dinner.vbs`") $* | 8U
}

#- Открытие страницы vimwiki в браузере
wiki() {
	url=$(cygpath -w //file-srv/homedir$/`whoami`/wiki/"`echo ${1:-index} | sed 's/_/ /g'`".html)
	cygstart -o "$url"
}

#- Телефонная книга TKPT
ab() {
	[ -z "$1" ] && addressbook_tkpt.bat | 8U || addressbook_tkpt.bat | 8U | grep "$*"
}

#- Для совместимости с wincmd
alias abs=ab #noindex

#- Внутренние номера без переадресации
alias abc="addressbook_check.bat | 8U"

#}}} ###########################################################################

#Переход в домашний каталог пользователя,
#если оболочка запущена в интерактивном режиме
#без изменения рабочей директории
[[ ("$-" == *i*) && ("$0" == bash) ]] && cd ~

