#!/bin/bash

#Создан:  Чтв 08 Июл 2010 17:45:51  YEKST
#Изменён: Втр 20 Июл 2010 19:54:35  YEKST

desc=$(
	command \help "$1" 2> /dev/null | grep "^$1[[:space:]()]*:" \
	| sed "s/^$1.*: //g" \
	| tr '\n' ' '
)

[ "$desc" == "" ] && desc=$(man /usr/man/man{1,2,4,5,6,7,8}/$1* 2>/dev/null \
	| cat -v - \
	| sed -r 's/.\^H|^\s+//g' \
	| sed -n '/^SYNOPSIS/{n;p}'
)

# alias
# type


echo -n "$desc"

